# Generated by Django 3.1.1 on 2020-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('Date', models.DateField(default=None)),
                ('Costumer_Id', models.IntegerField(default=0)),
                ('Costumer_Name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Alt_email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('Alt_phone', models.IntegerField(default=0)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Service', models.CharField(default='', max_length=100)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
