# Generated by Django 3.1.1 on 2020-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0002_auto_20201111_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
