# Generated by Django 3.1.1 on 2020-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0003_auto_20201111_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='Date',
            field=models.DateField(),
        ),
    ]
