# Generated by Django 3.1.1 on 2020-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0005_auto_20201111_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='Date',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
