# Generated by Django 3.1.1 on 2020-11-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0006_auto_20201111_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='Date',
        ),
    ]
