# Generated by Django 3.1.1 on 2020-11-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0007_remove_salesdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='Date',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
