# Generated by Django 3.1.1 on 2020-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0008_salesdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='Price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
