# Generated by Django 3.1.1 on 2020-11-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0009_auto_20201113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
