# Generated by Django 4.2.4 on 2023-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0011_auto_20201214_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
